### ISSUE TITLE
error when passing date with single digit day

### ISSUE THREAD

**Issue by jcspeegs** [jcspeegs/disneyland-reservation-checker#5]
When passing a single digit day to the start or end options, get error
```shell
./disneyland_reservation_checker.py -s 2021-11-9
```

> Traceback (most recent call last):
>   File "/home/ugflows/dev/disneyland_reservation_checker/./disneyland_reservation_checker.py", line 161, in <module>
>     main()
>   File "/home/ugflows/dev/disneyland_reservation_checker/./disneyland_reservation_checker.py", line 156, in main
>     calendar.notify(stdout=True)
>   File "/home/ugflows/dev/disneyland_reservation_checker/./disneyland_reservation_checker.py", line 94, in notify
>     self.notify_stdout()
>   File "/home/ugflows/dev/disneyland_reservation_checker/./disneyland_reservation_checker.py", line 101, in notify_stdout
>     print(self)
>   File "/home/ugflows/dev/disneyland_reservation_checker/./disneyland_reservation_checker.py", line 52, in __str__
>     park = ' and '.join(day['parks'])
> KeyError: 'parks'

**Comment by jcspeegs** [comment]
completed
